### ISSUE TITLE
Unele clipuri nu functioneaza

### ISSUE THREAD

**Issue by akaleeroy** [andiraduta/plugin.video.990ro#3]
Aparent clipurile vechi care sunt în format .flv nu pot fi redate.

Eroarea din **kodi.log**:
`23:10:25 T:5388   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://sv9.fastupload.ro/download/430deb803554c32881ba0c10c5d6aac8/55355d1c/flv/60eb7ed4dac7bcb24a806897415909e6.flv?.flv|referer=http://superweb.ro/video/60eb7ed4dac7bcb24a806897415909e6.html`

Fișierul există pe server, am verificat din browser.

**Comment by andiraduta** [comment]
Da, acum ceva timp facusem o modificare si adaugasem header-ul Referer la link-ul clipului. L-am scos.
Pare sa fie ok acum, merg si clipurile vechi si cele noi.
https://github.com/andiraduta/plugin.video.990ro/archive/v1.0.9.zip
